version: "3.3"

services:

  portainer:
    container_name: portainer
    network_mode: "bridge"
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    deploy:
        resources:
            limits:
              cpus: '0.02'
              memory: 30M 
            reservations:
              cpus: '0.0005'
              memory: 10M 
volumes:
  portainer_data: