version: "2"

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 49306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=<your_password>
      - MYSQL_PASSWORD=<your_password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:
        resources:
            limits:
              cpus: '0.05'
              memory: 160M 
            reservations:
              cpus: '0.0050'
              memory: 100M 
  app:
    image: nextcloud
    container_name: nextcloud
    network_mode: "bridge"
    volumes:
      - ./_data:/var/www/html
      - ./_data/apps:/var/www/html/custom_apps
      - ./_data/config:/var/www/html/config
      - ./_data/data:/var/www/html/data
      - ./_data/themes:/var/www/html/themes
    ports:
      - 49166:80
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.05'
              memory: 400M 
            reservations:
              cpus: '0.0050'
              memory: 300M 