version: "3"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1 #optional
     # - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com #optional
    volumes:
      - ./config:/config
    ports:
      - 8080:80
    restart: unless-stopped
    deploy:
        resources:
            limits:
              cpus: '0.05'
              memory: 100M
            reservations:
              cpus: '0.0005'
              memory: 50M