version: "3.0"
services:
  webdav-aliyundriver:
    image: zx5253/webdav-aliyundriver
    container_name: aliyundriver
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai
      - ALIYUNDRIVE_REFRESH_TOKEN=refreshToken
      - ALIYUNDRIVE_AUTH_USER-NAME=admin
      - ALIYUNDRIVE_AUTH_PASSWORD=admin_password
      - JAVA_OPTS=-Xmx512m
    volumes:
      - /usr/local/bin/docker/aliyundriver/:/etc/aliyun-driver/
    ports:
      - 49188:8080
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.10'
              memory: 365M 
            reservations:
              cpus: '0.0050'
              memory: 250M     